### ISSUE TITLE
Support for <xi:include> needed

### ISSUE THREAD

**Issue by CaptainPalapa** [nikku/node-xsd-schema-validator#10]
If XSD requires:
```
<bob>
   <fred>x</fred>
</bob>
```

And XML has:
```
<bob>
   <xi:include href="./people/fred.xml" parse="xml"/>
</bob>
```

Error is thrown:
`[error] cvc-complex-type.2.4.a: Invalid content was found starting with element 'xi:include'. One of '{"http://domaincom":fred}' is expected.`

Support for xi:include is super important for larger XML/XSD collections.  (Note, Altova XML spy correctly processes the includes and validates, if you need a non-code-based check.)

**Comment by nikku** [comment]
We accept pull requests on this feature.
