### ISSUE TITLE
Validator hangs if something other than a string or readable stream is passed in as xml parameter

### ISSUE THREAD

**Issue by ajkerr** [nikku/node-xsd-schema-validator#12]
Version 0.5.0 now hangs if something other than a stream, string, or Object with a file property is passed in for the xml parameter.

Other generic types of Objects used to be supported as well, and would just have their toString() output used as the XML.

We discovered this after upgrading to 0.5.0 because our code was passing in a Buffer returned from fs.readFile().

Happy to cook up a PR if it's helpful.

**Comment by nikku** [comment]
Buffers should be supported, too. 

I'm happy to merge a PR adding official support :wink:.
