### ISSUE TITLE
Not presenting expected errors 

### ISSUE THREAD

**Issue by Heucles** [nikku/node-xsd-schema-validator#14]
When addged soap envelope, it stopped showing errors such as data type validation and invalid tags name or tags missing. 
What I did was, added this tag :
```<xs:import namespace="http://schemas.xmlsoap.org/soap/envelope/" schemaLocation="soap-envelope.xsd"/>```
at the ".xsd" file and then is stoped presenting errors to me, is this a known berraviour?

**Comment by nikku** [comment]
This is related to https://github.com/nikku/node-xsd-schema-validator/issues/10.

Right now, we don't support external file includes, neither as part of the model, nor as part of the schema.
