### ISSUE TITLE
Spawn error

### ISSUE THREAD

**Issue by dobobaie** [nikku/node-xsd-schema-validator#15]
Hi !

Can you add this code : 
`        .on('error', function(err) {
           callback(new Error(err));
        });
`

After spawn function (line: 34 file: validator.js) because when spawn failed sometime exit event is not called and we can't debug without error event.

Thank you !

**Comment by nikku** [comment]
I'm not quite sure that I understand which scenario you're trying to support here. Under which circumstances does spawning fail?

Anyway, I'd accept a pull request regarding this change if you provide a [test case](https://github.com/nikku/node-xsd-schema-validator/blob/master/test/validator.js) with it.
