### ISSUE TITLE
FreeBSD11x64: validation problem

### ISSUE THREAD

**Issue by a5ter0id** [nikku/node-xsd-schema-validator#16]
Good afternoon, in attached [SchemaValidator.zip](https://github.com/nikku/node-xsd-schema-validator/files/2053504/SchemaValidator.zip) is the sample of validation xml file.

**Validation on Windows10x64 platform without any problem:**
D:\Temp\SchemaValidator>node example.js
Example is OK!

checking by XmlPad also without any problem

**Some problem with validation on FreeBSD11x64 platform:**
admin@:/usr/home/admin/NodeJs-Projects/SchemaValidator# node example.js
Error: invalid xml (status=WITH_ERRORS)
    at buildError (/usr/home/admin/NodeJs-Projects/SchemaValidator/node_modules/xsd-schema-validator/lib/validator.js:158:14)
    at finish (/usr/home/admin/NodeJs-Projects/SchemaValidator/node_modules/xsd-schema-validator/lib/validator.js:124:34)
    at ChildProcess.<anonymous> (/usr/home/admin/NodeJs-Projects/SchemaValidator/node_modules/xsd-schema-validator/lib/validator.js:164:7)
    at ChildProcess.emit (events.js:180:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)

**uname -a**: FreeBSD  11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**java -version:** openjdk version "1.7.0_161"
OpenJDK Runtime Environment (build 1.7.0_161-b01)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**printenv | grep JAVA**    JAVA_VERSION=1.7+
JAVA_HOME=/usr/local/openjdk7

**ls -l /usr/local/openjdk7**
total 22436
-r--r--r--   1 root  wheel      1503 10 мая   16:17 ASSEMBLY_EXCEPTION
drwxr-xr-x   2 root  wheel      1536 30 мая   16:54 bin
drwxr-xr-x  10 root  wheel       512 30 мая   16:54 demo
drwxr-xr-x   3 root  wheel       512 30 мая   16:54 include
drwxr-xr-x   4 root  wheel       512 30 мая   16:54 jre
drwxr-xr-x   2 root  wheel       512 30 мая   16:54 lib
-r--r--r--   1 root  wheel     19263 10 мая   16:17 LICENSE
drwxr-xr-x   4 root  wheel       512 30 мая   16:54 man
-rw-r--r--   1 root  wheel        79 10 мая   16:17 release
drwxr-xr-x   7 root  wheel       512 30 мая   16:54 sample
-rw-r--r--   1 root  wheel  22703291 10 мая   16:17 src.zip
-r--r--r--   1 root  wheel    172273 10 мая   16:17 THIRD_PARTY_README

**Checking JAVA - HelloWorld.java**
public class HelloWorld {
    public static void main(String[] args) {
            System.out.println("Hello World!");
    }
}
admin@:/usr/home/admin/NodeJs-Projects# javac HelloWorld.java
admin@:/usr/home/admin/NodeJs-Projects# java HelloWorld
Hello World!

**Comment by nikku** [comment]
Works on Arch Linux without problems:

```sh
$ node example.js
Example is OK!
```

May it be related to the fact that the FreeBSD system language is Russian? I don't believe so but cannot think of another reason either.

**Comment by a5ter0id** [comment]
I use UTF-8, and it seems strange that validation depends on lang.
I have created simple test [Java_Example.zip](https://github.com/nikku/node-xsd-schema-validator/files/2056430/Java_Example.zip) on JAVA for freebsd11x64 and no problem:

admin@:/usr/home/admin/NodeJs-Projects/Java# uname -a && javac DocbookXSDCheck.java && java DocbookXSDCheck
FreeBSD  11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
Example is valid.
