### ISSUE TITLE
Use of Java Incompatible with AWS Lambda

### ISSUE THREAD

**Issue by shellscape** [nikku/node-xsd-schema-validator#20]
Because of the use of java with `XMLValidator.java`, this package cannot be used in a Node Lambda environment.  There's not much else to report on this. Please consider using something other than a java file within this Node package.

**Comment by nikku** [comment]
The description of this library clearly states the dependency:

> A (XSD) schema validator for NodeJS that uses Java to perform the actual validation.

Please consider using another library that does the job for you in that specific environment.

Or be constructive and contribute an alternative, non-Java version.

Thanks!

**Comment by shellscape** [comment]
> Or be constructive

Haha nice. Not after that comment my friend.

**Comment by nikku** [comment]
To give you a few pointers why this cannot be accomplished easily, using NodeJS only can be found in the [why section](https://github.com/nikku/node-xsd-schema-validator#why).

This library aims to be a complete schema validation solution and priorizes that over being a NodeJS only solution.
