### ISSUE TITLE
Can't find the xsd file

### ISSUE THREAD

**Issue by alexvrv** [nikku/node-xsd-schema-validator#26]
__Describe the Bug__
The function seem to not be able to find the xsd file. Any path or xml i give to it, i get the same error: Error: invalid xml (status=WITH_ERRORS)

- Host (Browser/Node version), if applicable: Chrome 94
- OS: Windows 10
- Library version: 0.7.0

**Comment by nikku** [comment]
This library is [decently test covered](https://github.com/nikku/node-xsd-schema-validator/tree/master/test). 

Please provide details that allow me to reproduce your issue, I'll otherwise not be able to follow up.
