### ISSUE TITLE
XSD validation inside bpmnlint-playground

### ISSUE THREAD

**Issue by tboni91** [nikku/node-xsd-schema-validator#27]
__Is your feature request related to a problem? Please describe__

I'm currently using the <a href="https://github.com/bpmn-io/bpmnlint-playground">bpmnlint-playground</a> tool which uses <a href="https://github.com/bpmn-io/bpmn-js">bpmn-js</a> and <a href="https://github.com/bpmn-io/bpmnlint">bpmnlint</a> inside. What I would like to implement within bpmnlint-playground is the XSD validation of the bpmn model that is imported. Is it possible to use your library to do this?
Thanks in advance.

**Comment by tboni91** [comment]
Sorry for my mistake about the issue, do I have to close it and do it again?

**Comment by nikku** [comment]
@tboni91 Sorry for the late follow up. 

It is not easily possible to integrate this tool within what seems to be a client side browser app. This library by definition needs access to the file system to perform the XSD validation.

Depending on you're use-case (what would you like to accomplish with [bpmnlint-playground](https://github.com/bpmn-io/bpmnlint-playground)) I suggest you to open an issue over there.

**Comment by tboni91** [comment]
Hi @nikku,

my intent is to realize a custom validation system for bpmn models made by an editor that is completely client side, and I wanted to understand if it was possible to implement XSD validation in client side.An alternative, since it's not possible, I was thinking of implementing XSD schema constraints via custom bpmnlint rules but I don't know if it would have the same result.

**Comment by nikku** [comment]
> I wanted to understand if it was possible to implement XSD validation in client side.

There is many approaches, but that really depends on your use-case.

This library specifically targets NodeJS. Hence I was closing this issue.
