### ISSUE TITLE
Bitbucket pipeline: Error: Java SDK required at JAVA_HOME or in path to compile validation helper

### ISSUE THREAD

**Issue by ivcho02** [nikku/node-xsd-schema-validator#30]
Hi team,
Hope that you are well! 

I am trying to use this validator on a Bitbucket pipeline, but unfortunately, the build ends with the following error: 

**Error: Java SDK required at JAVA_HOME or in path to compile validation helper**

Docker image is:  node:10.15.3

I couldn't find a way to install java on the Bitbucket virtual machine. The error is thrown on the **_npm ci_** step when this dependency is tried to be installed. 

Do you have any ideas on how to install java-sdk from the **bitbucket-pipeline.yml** file?

ps.
It's working perfectly on my machine (I have java-sdk installed on my computer)

Kind Regards,
Ivo

**Comment by nikku** [comment]
I don't have an idea unfortunately I'd suggest you to use another docker image (that contains node _AND_ java).

**Comment by ivcho02** [comment]
Hi @nikku ,
Thanks for your reply, I will try to find such an image.

**Comment by ivcho02** [comment]
Hi team,
I found a **solution** without changing the docker image:

**_bitbucket-pipelines.yml_**

Before **npm install** put this: 

`script:
      # Install Java
      - apt-get update
      - apt-get install software-properties-common -y
      - add-apt-repository ppa:openjdk/ppa
      - apt-get install openjdk-8-jdk -y
      - npm ci`

Hope it helps. 

Best Regards,
Ivo

**Comment by ivanfretes** [comment]
I have the same error i verified my JAVA_HOME env but, this is ok
