### ISSUE TITLE
Async Support 

### ISSUE THREAD

**Issue by jesusdruizb** [nikku/node-xsd-schema-validator#32]
I am building a test framework that works asynchronously and it would be ideal to use this library since is so far the one that produces the most accurate and helpful results when validating and XML against an XSD.

Would an async implementation be considered?

Tried passing _done_ as a parameter and while it works it breaks the framework in other ways.

This for sure will be helpful to many others.

**Comment by nikku** [comment]
Happy to take a contribution that moves this to modern JavaScript (ditching the `done` callback completely)!
