### ISSUE TITLE
add type definitions for typescript

### ISSUE THREAD

**Issue by anthony-nhs** [nikku/node-xsd-schema-validator#36]
### Is your feature request related to a problem? Please describe

It would be useful to have a validator.d.ts file that contains type definitions so this package can easily be used in typescript projects

### Describe the solution you'd like

Add validator.d.ts file with type definitions

### Describe alternatives you've considered

There is @types/xsd-schema-validator but this does not work with 0.8.x versions

**Comment by nikku** [comment]
Released with v0.9.0. Sorry for the long idle time! :slightly_smiling_face:
