### ISSUE TITLE
WITH_ERRORS result 

### ISSUE THREAD

**Issue by token97** [nikku/node-xsd-schema-validator#4]
hey. 
i try to use your validator, but for each test i always get the same response : { valid: false, result: 'WITH_ERRORS', messages: [] } even if the xml is valid (I test on several online xml validator).
<pre>
var xmlStr = '<xmp><?xml version="1.0"?><comment><author>author</author><content>nothing</content></comment></xmp>';

validator.validateXML(xmlStr , schemaPath , function(err, result) {
                console.log(result);
                if (err) {
                    throw err;
                }
                result.valid; // true
            });
</pre>
this is the shema content (replacing "()" by "<>"):
<pre> (xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema")(xs:element name="comment")(xs:complexType)(xs:all)(xs:element name="author" type="xs:string"/)(xs:element name="content" type="xs:string"/)(/xs:all)(/xs:complexType)(/xs:element)(/xs:schema)</pre>

Same issue when I'm using examples into validatorSpec with BPMN20.xsd...

**Comment by nikku** [comment]
What is your java / nodejs runtime / operating system version?

Does the test suite (`grunt test`) pass for you?
