### ISSUE TITLE
Failed to compile helper (exitCode=2)

### ISSUE THREAD

**Issue by RovoMe** [nikku/node-xsd-schema-validator#48]
### Describe the Bug

Using following typescript code

```typescript
import * as validator from 'xsd-schema-validator';

...

private async validateXML(pathToXml: string, pathToXsd: string): Promise<boolean> {
    try {
        const xmlString: string = await fs.readFile(pathToXml, 'utf-8');
        const result = await validator.validateXML(xmlString, pathToXsd);
        if (result.valid) {
            return result.valid;
        }
        warn(`Validation of file ${pathToXml} failed due to ${JSON.stringify(result.messages, null, 2)}`);
    } catch (err) {
        error(`Validation of file ${pathToXml} failed: ${errorMessage(err)}`);
    }
    return false;
}
```
to validate an XML document against a XSD file fails with

```console
Error: Failed to compile helper (exitCode=2) {stack: 'Error: Failed to compile helper (exitCode=2)
…Trampoline (node:internal/async_hooks:130:17)', message: 'Failed to compile helper (exitCode=2)'}
```

This error also occurs when I add 

```typescript
await validator.setup();
```

before the `validateXML` function is called. Here the error message then looks as such:

```console
rejected promise not handled within 1 second: Error: Failed to compile helper (exitCode=2)
extensionHostProcess.js:162
stack trace: Error: Failed to compile helper (exitCode=2)
	at ChildProcess.<anonymous> (.../out/extension.js:7535:15)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess._handle.onexit (node:internal/child_process:294:12)
	at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

and occurs right at that `setup()` call.

I checked the whole setup further as the exit code 2 seems to come from the `javac` invocation which translate to `File not found`. When I check the `xsd-schema-validator` component inside the `nodes_modules` folder I actually see the respective `XMLValidator.class` inside the `support` subdirectory and decompiling the class also works.

![Bildschirmfoto 2024-11-18 um 19 39 13](https://github.com/user-attachments/assets/7da03f97-08b6-475c-aaac-78bd3c671aa8)

As [this code](https://github.com/nikku/node-xsd-schema-validator/blob/main/lib/validator.js#L34-L40) should skip a compilation of the Java class when already a `XMLValidator.class` exists, which as shown should exist actually, I think there must be an issue somehow with the path in general. Unfortunately, I only see the error log within VSCodes host extension output but nothing other.

Running the following Java command from the root of the project seems to work:

```console
% java -cp ./node_modules/xsd-schema-validator support.XMLValidator
[error] specify schema via -schema=[SCHEMA]
```

Even the new approach to auto-compile it via 

```console
% java ./node_modules/xsd-schema-validator/support/XMLValidator.java
[error] specify schema via -schema=[SCHEMA]
```
works.

### Environment

- Host: VSCode 1.95.0 - extension 
- OS: MacOS Sonomo 14.7.1
- Node: v21.7.1
- Typescript: 4.9.5 (can't go higher due to outdated `xslt-ts` version)
- xsd-schema-validator: 0.9.0
- @types/xsd-schema-validator: 0.5.7

```console
% java --version
java 21.0.3 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)
% javac --version
javac 21.0.3
% whereis java
java: /usr/bin/java
% whereis javac
javac: /usr/bin/javac
% echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/
```

**Comment by RovoMe** [comment]
After changing `validator.d.ts` locally to

```typescript
import { Readable as ReadableStream } from "stream";

export type ValidateResult = {
    valid: boolean;
    result: string;
    messages: string[];
};

export type Options = {
    cwd: string;
    debug: boolean;
};

export class Validator {

    constructor(options = undefined || Options);

    validateXML(
        xml: string | Buffer| ReadableStream | { file: string },
        pathToXsd: string
    ): Promise<ValidateResult>;
}

/**
 * @internal
 */
export function setup(): Promise<void>;
```

And changing the following two constants in `validator.js`

```js
const BASE_DIR = path.resolve(__dirname, '../node_modules/xsd-schema-validator');

const VALIDATOR = path.resolve(BASE_DIR, 'support/XMLValidator');
```

And then the actual validation call within the VSCode extension to 

```typescript
const validator = new Validator({debug: true});
const result = await validator.validateXML(xmlString, pathToXsd);
```

the validation of XML files according to a given XSD now works. I feel though that these changes might be a bit to much. Especially the `cwd` option property is not taken as a base for the remaining `validator.js` logic, unforunately.

**Comment by nikku** [comment]
Please report back the debug output you're seeing when executing

```
LOG_DEBUG=xsd-schema-validator npm install
```

**Comment by nikku** [comment]
Instead of altering the source code massively, add some reasonable `console.log()` statements to understand what the tool finds and what it does not find.

**Comment by RovoMe** [comment]
> Please report back the debug output you're seeing when executing

I deleted the whole `node_modules` directory and then performed the requested command and this is the output I get:

```console
% LOG_DEBUG=xsd-schema-validator npm install
npm WARN deprecated simple-git-types@1.53.10: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated fstream@1.0.12: This package is no longer supported.
npm WARN deprecated vscode-extension-tester-locators@3.12.2: Deprecated - This package was replaced by @redhat-developer/locators
npm WARN deprecated monaco-page-objects@3.14.1: Deprecated - This package was replaced by @redhat-developer/page-objects
npm WARN deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.

added 852 packages, and audited 853 packages in 4s

206 packages are looking for funding
  run `npm fund` for details

1 critical severity vulnerability

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

Except for `vscode-extension-tester` and `eslint` all reported warnings are for transitive dependencies.

I checked all ouput consoles of VSCode and even checked the developer console but no logs are visible in regards to `xsd-schema-validator` from what I can tell.

 > Instead of altering the source code massively, add some reasonable console.log() statements to understand what the tool finds and what it does not find.

I now just modifed `validator.js` in `moule.exports.validateXML = ...` to set `const debug = true;` and added 

```js
  console.log(`BASE_DIR: ${BASE_DIR}`);
  console.log(`VALIDATOR: ${VALIDATOR + '.class'}`);
```

to the start of `async function withValidator(debug) {...}`. 

And this is the output I receive: 

```console
BASE_DIR: /path/to/MyProject
VALIDATOR: /path/to/MyProject/support/XMLValidator.class
Compiling helper
Found javac: /Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/javac
Error: Failed to compile helper (exitCode=2) {stack: 'Error: Failed to compile helper (exitCode=2)
…Trampoline (node:internal/async_hooks:130:17)', message: 'Failed to compile helper (exitCode=2)'}
```

As can be seen, the base dir (set by the `__dirname` value) points to the project root but not the `xsd-schema-validator` node module (should probably be `/path/to/MyProject/node_modules/xsd-schema-validator`) and as such, also the `VALIDATOR` constant is therefore missing this part in the path and as such fails the lookup (and compilation) of the Java class.

As the exported `validateXML` function only accepts the XML and the XSD files as input, the path itself cannot be redefined here, at least not from a pure Typescript stance.

**Comment by nikku** [comment]
You could execute `npm install --verbose` to get post install output. 

Do you by any chance transpile the sourcecode of your project? This will likely break `__dirname` references, which need to be kept as the original.

**Comment by nikku** [comment]
> The --bundle option basically includes every import it finds recursively starting from the ./src/extension.ts into the out/extension.js file. This is probably causing the problems, 

Indeed that is the case. Bundling inadvertedly changes `__dirname`, and as a result the helper can no longer be retrieved. 

Leaving `xsd-schema-validator` as an external dependency should be a fine workaround for you. 

Thanks for providing the details. Closing this issue as won't fix.
